name: Build, push to Docker and trigger deployment
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Extract version and set it to TAG env var
        run: |
          echo "TAG=$(jq -r '.version' package.json)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/authsafe:latest
            ${{secrets.DOCKERHUB_USERNAME}}/authsafe:${{env.TAG}}

      - name: Trigger Deploy Webhook
        if: success()
        run: |
          curl -X GET ${{secrets.WEBHOOK_URL}}
