export enum CleanupAction {
  EXPIRED_TOKEN = "EXPIRED_TOKEN",
  PASSWORD_RESET_TOKEN = "PASSWORD_RESET_TOKEN",
  UNVERIFIED_ORGANIZATIONS = "UNVERIFIED_ORGANIZATIONS",
  UNVERIFIED_USERS = "UNVERIFIED_USERS",
  OLD_LOGS = "OLD_LOGS",
}
